# Numpy

## Numpy的ndarray：一种多维数组对象

NumPy最重要的一个特点就是其N维数组对象，该对象是一个快速而灵活的大数据集容器。你可以利用这种数组对整块数据执行一些数学运算，其语法跟标量元素之间的运算一样。

ndarray是一个通用的同构数据多维容器，也就是说，其中的所有元素必须是相同类型的。每个数组都有一个shape（一个表示各维度大小的元组）和一个dtype（一个用于说明数组数据类型的对象）。

## 创建ndarray

创建数组最简单的办法是使用array函数。它接受一切序列型的对象（包括其他数组），然后产生一个新的含有传入数据的NumPy数组。以一个列表的转换为例：

In [1]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
#嵌套序列（比如由一组等长度列表组成的列表）将会转换为一个多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

除非显示说明，np.array会尝试为新建的这个数组推断出一个较为合适的数据类型。数据类型保存在一个特殊的dtype对象中

In [6]:
arr1.dtype

dtype('float64')

In [7]:
arr2.dtype

dtype('int64')

除np.array之外，还有一些函数也可以新建数组。比如，zeros和ones分别可以创建指定长度或形状的全0或全1数组。empty可以创建一个没有任何具体值的数组。

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

np.empty返回的是一些未初始化的垃圾值

In [10]:
np.empty((2, 3, 2))

array([[[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,              nan],
        [-1.28822975e-231, -1.28822975e-231]]])

arange是Python内置函数range的数组版

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## ndrray的数据类型

dtype（数据类型）是一个特殊的对象，它含有ndarray将一块内存解释为特定数据类型所需的信息。

In [15]:
arr1=np.array([1,2,3],dtype=np.float64)
arr1

array([1., 2., 3.])

dtype是NumPy如此强大和灵活的原因之一。多数情况下，它们直接映射到相应的机器表示，这使得“读写磁盘上的二进制数据流”以及“集成低级语言代码（如C，Forrtan”等工作变得更加容易。

你可以通过ndarray的astype方法显示地转换其dtype

如果转换浮点数成整数，则小数部分会被截断

In [16]:
arr = np.array([3.7, 1.2, -2.5])

arr.astype(np.int32)

array([ 3,  1, -2], dtype=int32)

如果转换过程因为某种原因而失败了，就会引发一个TypeError。

调用astype无论如何都会创建出一个新的数组（原始数据的一份拷贝），即使新dtype跟老dtype相同也是如此。

## 数组和标量之间的运算

数组很重要，因为它使你不用编写循环即可对数据进行批量运算。这通常叫做矢量化。大小相等的数组之间的任何算术运算都会运算应用到元素级：

In [17]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [19]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

同样，数组与标量的算术运算也会将那个标量值传播到各个元素

In [20]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [21]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

不同大小的数组之间的运算叫做广播。

## 基本的索引和切片

NumPy数组的索引是一个内容丰富的主题，因为选取数据子集或单个元素的方式有很多。一维数组很简单。从表面上看，它们跟Python列表的功能差不多。

In [22]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[5]

5

In [24]:
arr[5:8]

array([5, 6, 7])

In [25]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

当你将一个标量赋值给一个切片时，该值会自动传播到整个选区。跟列表最重要的区别在于，数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到原数组上。由于NumPy的设计目的是处理大数据，如果将数据复制的化会产生性能和内存问题。

In [28]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    64, 12345,    64,     8,
           9])

In [29]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])



对于高维数组，能做的事情更多。在一个二维数组中，各索引位置上的元素不再是标量而是一维数组。

In [30]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d[1]

array([4, 5, 6])

可以对各个元素进行递归访问，但这样需要做的事情有点多。你可以传入逗号隔开索引列表来选取单个元素。

In [31]:
arr2d[0,2]

3

在多维数组中，如果省略了后面的索引，则返回对象是维度低一点的ndarray。

标量值和数组都可以赋值给高维数组

In [32]:
arr2d[1]=1
arr2d

array([[1, 2, 3],
       [1, 1, 1]])

In [34]:
arr2d[1]=arr2d[0].copy()
arr2d

array([[1, 2, 3],
       [1, 2, 3]])

## 切片索引

ndarray的切片语法跟Python列表这样的一维对象差不多：

In [36]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [37]:
arr[1:6]

array([1, 2, 3, 4, 5])

对于高维数组，切片是沿着一个轴的方向上去元素

In [42]:
arr2d=np.arange(6).reshape((2,3))
arr2d

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
arr2d[:1]

array([[0, 1, 2]])

In [44]:
arr2d[:1,1:]

array([[1, 2]])

向这样进行切片时，只能得到相同维度的数组视图。通过将整数索引和切片混合，可以得到低纬度的切片。

In [45]:
arr2d[1,:2]

array([3, 4])

In [46]:
arr2d[1,:1]

array([3])

注意，”只有冒号“表示选取整个轴。

## 布尔型索引

In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will'], dtype='<U4')

In [48]:
data = np.random.randn(5, 4)
data

array([[ 0.70442077, -0.58073306, -1.3220708 ,  1.15284063],
       [-2.06301153, -0.05206863,  2.33998266,  0.81055709],
       [-0.104694  , -0.56911113, -0.67507631, -0.9587267 ],
       [ 0.03666217, -0.94988515,  1.11645559,  0.54199208],
       [ 0.93061011,  2.71301235, -0.91122791,  0.72497535]])

In [49]:
names=='Bob'

array([ True, False, False,  True, False])

布尔型数组的长度必须跟索引的轴长度一致。

In [50]:
data[names=='Bob']

array([[ 0.70442077, -0.58073306, -1.3220708 ,  1.15284063],
       [ 0.03666217, -0.94988515,  1.11645559,  0.54199208]])

In [51]:
data[names == 'Bob',2:]

array([[-1.3220708 ,  1.15284063],
       [ 1.11645559,  0.54199208]])

In [52]:
data[names=='Bob',3]

array([1.15284063, 0.54199208])

可通过!=或~取反

In [53]:
names!='Bob'

array([False,  True,  True, False,  True])

In [54]:
data[~(names=='Bob')]

array([[-2.06301153, -0.05206863,  2.33998266,  0.81055709],
       [-0.104694  , -0.56911113, -0.67507631, -0.9587267 ],
       [ 0.93061011,  2.71301235, -0.91122791,  0.72497535]])

In [55]:
data[data < 0] = 0
data

array([[0.70442077, 0.        , 0.        , 1.15284063],
       [0.        , 0.        , 2.33998266, 0.81055709],
       [0.        , 0.        , 0.        , 0.        ],
       [0.03666217, 0.        , 1.11645559, 0.54199208],
       [0.93061011, 2.71301235, 0.        , 0.72497535]])

通过布尔型索引数组中的数据，将重视创建数据的副本，即使返回一摸一样的数组也是如此。

## 花式索引

利用整数数组进行索引

In [56]:
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

以特定顺序选取行子集，只需传入一个指定顺序的整数列表或ndarray即可：

In [57]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

使用负数索引将会从末尾开始选取行：

In [58]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

一次传入多个索引数组会有一点特别，它返回的是一个一维数组，其中的元素对应各个索引元组：

In [59]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [60]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [61]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

np.ix_函数，可以讲两个一维数组转换为一个用于选取方形区域的索引器：

In [62]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

花式索引和切片不一样，它总是讲数据复制到新数组中。

## 数组转置和轴对换

转置是重塑的一种特殊形式，它返回的是源数据的视图（不会进行任何复制操作）。数组不仅有transpose方法，还有一个特殊的T属性：

In [63]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

利用np.dot计算矩阵内积：

In [65]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置：

In [66]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [67]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

简单的转置可以使用.T，它其实就是进行轴对换而已。ndarray还有一个swapaxes方法，它需要接受一对轴编号：

In [69]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 通用函数：快速的元素级数组函数

通用函数（即ufunc）是一种对ndarray中的数据执行元素级运算的函数。你可以将其看做简单函数（接受一个或多个标量值，并产生一个或多个标量值）的矢量化包装器。

许多ufunc都是简单的元素级变体，如sqrt和exp：