   # Pandas

In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np


   ## pandas的数据结构
   要使用pandas，首先得熟悉它的两个主要数据结构：Series和DataFrame。
   ### Series
   Series是一种类似于一维数组的对象，它由一组数据（各种Numpy数据类型）以及一组与之相关的数据标签（即索引）组成。仅有一组数据即可产生最简单的Series：

In [2]:
obj = Series([4, 7, -5, 3])
obj


0    4
1    7
2   -5
3    3
dtype: int64

   Series的字符串表现形式为：索引在左边，值在右边。由于我们没有为数据指定索引，于是会自动创建一个0到N-1（N为数据的长度）的整数型索引。你可以通过Series的values和index属性获取其数组表示形式和索引对象：

In [3]:
obj.values



array([ 4,  7, -5,  3])

In [4]:
obj.index


RangeIndex(start=0, stop=4, step=1)

   通常 ， 我们希望所创建的Series带有一个可以对各个数据点进行标记的索引 ：

In [5]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2


d    4
b    7
a   -5
c    3
dtype: int64

   与普通Numpy数组相比，你可以通过索引的方式选取Series中的单个或一组值：

In [6]:
obj2['a']



-5

In [7]:
obj2['d'] = 6
obj2[['c', 'a', 'd']]


c    3
a   -5
d    6
dtype: int64

   Numpy数组运算（如根据布尔型数组进行过滤，标量乘法，应用数学函数等）都会保留索引和值之间的链接：

In [8]:
obj2



d    6
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2[obj2 > 0]



d    6
b    7
c    3
dtype: int64

In [10]:
obj2 * 2



d    12
b    14
a   -10
c     6
dtype: int64

In [11]:
np.exp(obj2)


d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

   还可以将Series看成是一个定长的有序字典,因为它是索引值到数据值的一个映射。它可以用在许多原本需要字典参数的函数中：

In [12]:
'b' in obj2



True

In [13]:
'e' in obj2


False

   如果数据被存放在一个python字典中，也可以直接通过这个字典来创建Series：

In [14]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3


Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

   如果只传入一个字典，则结果Series中的索引了就是原字典的键（有序排列）。

In [15]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
obj4


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

 sdata中跟states索引相匹配的那三个值会被找出来并放到相应的位置上，
 但由于“Californai”所对应的sdata值找不到，所以其结果就为NaN（即“非数字”（not a number），
 在pandas中，它用于表示缺失或NA值）。pandas的isnull和notnull函数可以用来检测缺失数据：

In [16]:
pd.isnull(obj4)



California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [17]:
pd.notnull(obj4)


California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

   Series也有类似的实例方法：

In [18]:
obj4.isnull()


California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

   Series最重要的一个功能是：它在算术运算中会自动对其不同索引的数据。

In [19]:
obj3



Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [20]:
obj4



California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
obj3 + obj4


California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

   Series对象本身及其索引都有一个name属性，该属性跟pandas其他的关键功能关系非常密切：

In [22]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4


state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

   Series的索引可以通过赋值的方式就地修改：

In [23]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj


Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

   ## DataFrame
   DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值，字符串，布尔值等）。DataFrame既有行索引也有列索引，它可以被看做由Series组成的字典（共用同一个索引）。跟其他类似的数据结构相比，DataFrame中面向行和面向列的操作基本是平衡的，其实，DataFrame中的数据是以一个或多个二维块存放的。
   构建DataFrame的办法有很多，最常用的一种是直接传入一个由等长列表或Numpy数组组成的字典：

In [24]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame


state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

   结果DataFrame会自动加上索引，且全部列会被有序排列：
   如果指定了列序列，则DataFrame的列就会按照指定顺序进行排列：

In [25]:
DataFrame(data, columns=['year', 'state', 'pop'])


year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

   跟Series一样，如果传入的列在数据中找不到，就会产生NA值：

In [26]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=[
                   'one', 'two', 'three', 'four', 'five'])
frame2



year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [27]:
frame2.columns


Index(['year', 'state', 'pop', 'debt'], dtype='object')

   通过类似字典标记的方式或属性的方式，可以将DataFrame的列获取为一个Series：

In [28]:
frame2['state']



one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [29]:
frame2.year


one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

   返回的Series拥有原DataFrame相同的索引，且其name属性也已经被相应地设置好了。行可以通过位置或名称的方式进行获取，比如用索引字段loc：

In [30]:
frame2.loc['three']


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

   列可以通过赋值的方式进行修改。例如：我们可以给那个空的 “ debt ” 列赋上一个标量值或一组值：

In [31]:
frame2['debt'] = 16.5
frame2



year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [32]:
frame2['debt'] = np.arange(5.)
frame2


year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

   将列表或数组赋值给某个列时，其长度必须跟DataFrame的长度相匹配。如果赋值的是一个Series，就会精确匹配到DataFrame的索引，所有的空位都将会填上缺失值：

In [33]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2


year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

   为不存在的列赋值会创建出一个新列。关键字del用于删除列：

In [34]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2



year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [35]:
del frame2['eastern']
frame2.columns


Index(['year', 'state', 'pop', 'debt'], dtype='object')

   另一种常见的数据形式是嵌套字典（也就是字典的字典）：

In [36]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}


   如果将它传给DataFrame，它就会被解释为：外层字典的键作为列，内层键则作为行索引：

In [37]:
frame3 = DataFrame(pop)
frame3


Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

   也可以对结果进行转置

In [38]:
frame3.T


2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

   由Series组成的字典差不多也是一样的用法：

In [39]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)


Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

   如果设置了DataFrame的index和columns的name属性，则这些信息也会被显示出来：

In [40]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3


state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

   跟Series一样，values属性也会以二维ndarray的形式返回DataFrame中的数据：

In [41]:
frame3.values


array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

   如果DataFrame各列的数据类型不通，则值数据的数据类型就会选用能兼容所有列的数据类型：

In [42]:
frame2.values


array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

  ## 索引对象
  pandas的索引对象负责管理标签和其他元数据（比如轴名称等）。构建Series或DataFrame时，所用到的任何数组或其他序列的标签都会被转换成一个Index：

In [43]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index


Index(['a', 'b', 'c'], dtype='object')

  Index对象是不可修改的，因此用户不能对其进行修改：

In [44]:
index[1] = 'd'


TypeError: Index does not support mutable operations

  不可修改性非常重要，因为这样才能使Index对象在多个数据结构之间安全共享：

In [45]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index


True

  ## 基本功能
  ### 重新索引
  pandas对象的一个重要方法是reindex，其作用是创建一个适应新索引的新对象。

In [46]:
obj = Series([4.5, 7.2, -5.2, 3.6], index=['d', 'b', 'a', 'c'])
obj


d    4.5
b    7.2
a   -5.2
c    3.6
dtype: float64

  调用该Series的reindex将会根据新索引进行重排。如果某个索引值当前不存在，就引入缺失值：

In [47]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2


a   -5.2
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

  对于时间序列这样的有序数据，重新索引时可能需要做一些插值处理。method选项即可达到此目的，例如使用ffill可以实现前向值填充 ：

In [48]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')


0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

  对于DataFrame，reindex可以修改（行）索引，列，或两个都修改。如果仅传入一个序列，则会重新索引行：

In [49]:
frame = DataFrame(np.arange(9).reshape((3, 3)), index=[
                  'a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])
frame


Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [50]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2


Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

 使用columns关键字即可重新索引列:

In [51]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)


Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [52]:
frame.reindex(index=['a', 'b', 'c', 'd'], columns=states)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

 利用loc或iloc的标签索引功能,重新索引任务可以变得更简洁:

In [53]:
frame.loc[['a', 'b', 'c', 'd'], states]


/Users/mohenoo/Librarys/anaconda3/envs/python_36/lib/python3.6/site-packages/pandas/core/indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

 ###丢弃指定轴上的项
 丢弃某条轴上的一个或多个项很简单,只要有一个索引数组或列表即可.由于需要执行一些数据整理和集合逻辑,所以drop方法返回的是一个在执行轴上删除了指定值的新对象:

In [54]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj


a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

 对于DataFrame,可以删除任意轴上的索引值:

In [55]:
data = DataFrame(np.arange(16).reshape((4, 4)), index=[
                 'Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data.drop(['Colorado', 'Ohio'])


one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [56]:
data.drop('two', axis=1)


one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

 ### 索引,选取和过滤
 Series索引(obj[...])的工作方式类似于NumPy数组的索引,只不过Series的索引值不只是整数.

In [57]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj


a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [58]:
obj['b']


1.0

In [59]:
obj[1]


1.0

In [60]:
obj[2:4]


c    2.0
d    3.0
dtype: float64

In [61]:
obj[['b', 'a', 'd']]


b    1.0
a    0.0
d    3.0
dtype: float64

In [62]:
obj[[1, 3]]


b    1.0
d    3.0
dtype: float64

In [63]:
obj[obj < 2]


a    0.0
b    1.0
dtype: float64

 利用标签的切片运算与普通的Python切片运算不同,其末端是包含的.

In [64]:
obj['b': 'c']


b    1.0
c    2.0
dtype: float64

 设置的方式也很简单

In [65]:
obj['b': 'c'] = 5
obj


a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

 如你所见, 对DataFrame进行索引其实就是获取一个或多个列:

In [66]:
data = DataFrame(np.arange(16).reshape((4, 4)), index=[
                 'Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [67]:
data['two']


Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [68]:
data[['three', 'one']]


three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

 这种索引方式有几个特殊的情况.首先通过切片或布尔型数组选区行:

In [69]:
data[:2]


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [70]:
data[data['three'] > 5]


one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

 另一种用法是通过布尔型DataFrame,进行索引:

In [71]:
data < 5


one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [72]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

 可以通过loc,iloc, 实现NumPy式的标记法以及轴标签从DataFrame中选取行和列的子集.

In [73]:
data.loc['Colorado', ['two', 'three']]


two      5
three    6
Name: Colorado, dtype: int64

In [74]:
data


one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [75]:
data.iloc[[2, 3], [3, 0, 1]]


four  one  two
Utah        11    8    9
New York    15   12   13

 也就是说,对pandas对象中的数据的选取和重排方式很多.
 ## 算术运算和数据对齐
 pandas最重要的一个功能是,它可以对不同索引的对象进行算术运算.在将对象相加时,如果存在不同的索引对,则结果的索引就是该索引对的并集.

In [76]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s1


a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [77]:
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s2


a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [78]:
s1+s2


a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

 自动的数据对其操作在不重叠的索引处引入了NA值.缺失值会在算术运算过程中传播.
 对于DataFrame,对齐操作会同时发生在行和列上:

In [79]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns=list(
    'bcd'), index=['Ohio', 'Texas', 'Colorado'])
df1


b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [80]:
df2 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list(
    'bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df2


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [81]:
df1+df2


b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

 ## 在算术方法中填充值
 在对不同索引的对象进行算术运算时,你可能希望当一个对象中某个轴标签在另一个对象中找不到时填充一个特殊值.

In [82]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df1



a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [83]:
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df2


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [84]:
df1+df2


a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [85]:
df1.add(df2, fill_value=0)


a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

 与此类似,在到Series或DataFrame重新索引时,也可以指定一个填充值:

In [86]:
df1.reindex(columns=df2.columns, fill_value=0)



a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

 ### DataFrame和Series之间的运算
 跟NumPy数组一样,DataFrame和Series之间算术运算也是有明确规定的.

In [87]:
arr = np.arange(12.).reshape((3, 4))
arr


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [88]:
arr[0]


array([0., 1., 2., 3.])

In [89]:
arr-arr[0]


array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

 这就叫做广播.

In [90]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list(
    'bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [91]:
series = frame.iloc[0]
series


b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

 默认情况下,DataFrame和Series之间的算术运算会将Series的索引匹配到DataFrame的列,然后沿着行一直向下广播:

In [92]:
frame-series


b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

 如果某个索引值在DataFrame的列或Series的索引中找不到,则参与运算的两个对象就会被重新索引以形成并集:

In [93]:
series2 = Series(range(3), index=list('bef'))
series2


b    0
e    1
f    2
dtype: int64

In [94]:
frame+series2


b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

 如果你希望匹配行且在列上广播,则必须使用算术运算方法.

In [95]:
series3 = frame['d']
series3


Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [96]:
frame


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [97]:
frame.sub(series3, axis=0)


b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

 传入的轴号就是希望匹配的轴.